export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

export const COMENZAR_DESCARGA_PRODCUTO = 'COMENZAR_DESCARGA_PRODCUTO';
export const DESCARGAR_PRODUCTOS_EXITOS = 'DESCARGAR_PRODUCTOS_EXITOS';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const OBTENER_PRODCUTO_ELIMINAR = 'OBTENER_PRODCUTO_ELIMINAR';
export const PRODCUTO_ELIMINAR_EXITO = 'PRODCUTO_ELIMINAR_EXITO';
export const PRODCUTO_ELIMINAR_ERROR = 'DESCARGA_PRODUCTOS_ERROR';
